# Generated by Django 3.0.5 on 2020-10-27 02:40

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], max_length=7)),
                ('role', models.CharField(choices=[('normal', 'Normal'), ('admin', 'Admin')], max_length=6)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('last_login_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
